package com.wipro.onetomany.entity;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

@Entity
@Table(name="students")
public class Student {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	private String name;
	
	//Unidirectional one-to-one mapping with ReportCard
	@OneToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="reportcard_id") // fk in Student table ( which shows that student has a reference of Report Card)
	private ReportCard reportcard;
	
	
      //Unidirectional one-to-many mapping with courses
		@OneToMany(cascade=CascadeType.ALL)
		@JoinColumn(name="student_id") // fk in course table ( which shows that student has a reference of Report Card)
		private List<Courses> courses = new ArrayList<>();

	
	public List<Courses> getCourses() {
			return courses;
		}

	public void addCourse(Courses c)
	{
		this.courses.add(c);
	}
	public Student() {
		super();
		// TODO Auto-generated constructor stub
	}

	// id will autogenerated and report card we will get from child entity
	public Student(String name) {
		super();
		this.name = name;
	}

	// setter injection will take place
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ReportCard getReportcard() {
		return reportcard;
	}

	public void setReportcard(ReportCard reportcard) {
		this.reportcard = reportcard;
	}

	@Override
	public String toString() {
		return "Student [id=" + id + ", name=" + name + ", reportcard=" + reportcard + "]";
	}
	
	
	

}
