spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallBack
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallback
      default-filters:
      - name: CircuitBreaker
        args:
          name: defaultCircuitBreaker
          fallbackUri: forward:/defaultFallback          

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
            
resilience4j:
  circuitbreaker:
    instances:
      order-service:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
      payment-service:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
      defaultCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50